# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=net.ezeq.gorinnosho

# Dependencies
fabric_api_version=0.116.14+1.21.1
cloth_config_version=15.0.140
spell_engine_version=1.9.14+1.21.1-fabric
spell_power_version=1.5.0+1.21.1-fabric
player_anim=2.0.4+1.21.1
trinkets_version=3.10.0-fabric
cca_version = 6.1.3
sengoku_jidai_version=2.1.4+1.21.1-fabric
emf_version=3.2.4-fabric-1.21
etf_version=7.1-fabric-1.21
continuity_version=3.0.0+1.21
lithostitched_version=1.7.13-fabric-21.1
polytone_version=1.21-3.9.1-fabric
tinyconfig_group=maven.modrinth
tinyconfig_slug=tiny-config
tinyconfig_version=3.1.1-fabric
moonlight_group=maven.modrinth
moonlight_slug=moonlight
moonlight_version=1.21.1-3.1.1
codecui-fabric_version=1.21.1-1.1.5
exp4j_version=0.4.8
mvel_version=2.5.2.Final
azurelib_version=3.1.11
defaulted_version=1.3.8
java-diff-utils_version=4.17
yo_hooks_version=4.6.2
jei_version=19.39.0.372
bettercombat-fabric_version=2.4.0+1.21.1